### ISSUE TITLE
这个可以直接同一个定向多个属性的查询吗？

### ISSUE THREAD

**Issue by paulllb** [csimplestring/bool-expr-indexer#2]
比如说有一个定向是 喜好 羽毛球、篮球、网球 等等
来了一个用户，他的标签是 喜好 羽毛球、篮球 这种我看没法直接检索吧？

**Comment by csimplestring** [comment]
你是说有一个定向：“网球 and 篮球 and 羽毛球”。用户的标签是 “羽毛球 and 篮球”，少了一个网球，对吗？

这个情况确实无法匹配，但是一般的广告系统中，会有一个统计模块，来统计miss hit的数据，一段时间后需调整定向的表达式，来接近那些miss的用户。

**Comment by paulllb** [comment]
少了一个网球不是重点，重点是用户是有统一定向的两个属性值 羽毛球和篮球，这个在match模块我发现会出现召回出错误的情况
比如说 ：
A 广告 定向了 性别：男，爱好：羽毛球和篮球

**Comment by csimplestring** [comment]
能否贴一段代码让我看看？主要就是广告定向的条件和用户的标签的代码是如何表示的，最好能直接写个test，可以帮你看看问题在哪里

**Comment by paulllb** [comment]
func Test_MemReadOnlyIndex_Match(t *testing.T) {

    var conjunctions []*expr.Conjunction

    conjunctions = append(conjunctions, expr.NewConjunction(
        1,
        []*expr.Attribute{
            {Name: "age", Values: []string{"3"}, Contains: true},
            {Name: "state", Values: []string{"NY", "CH"}, Contains: true},
        },
    ))

    k, err := indexer.NewMemReadOnlyIndexer(conjunctions)
    assert.NoError(t, err)
    k.Build()

    assert.Equal(t, 2, k.MaxKSize())
    matcher := &allMatcher{}

    matched := matcher.Match(k, expr.Assignment{
        expr.Label{Name: "age", Value: "4"},
        expr.Label{Name: "state", Value: "NY"},
        expr.Label{Name: "state", Value: "CH"},
    })

    assert.ElementsMatch(t, []int{1}, matched)
}

**Comment by csimplestring** [comment]
@paulllb  谢谢这个test case，知道看到这个例子我才理解了这个issue题目的意图，

简单来讲，这个算法不支持“一个定向多个属性的查询”，例如你提供的state的两个查询
```
expr.Assignment{
    expr.Label{Name: "age", Value: "4"},
    expr.Label{Name: "state", Value: "NY"},
    expr.Label{Name: "state", Value: "CH"},
})
```

详细的来讲：
由于Assignment中后两个label被拆开了
```
    expr.Label{Name: "state", Value: "NY"},
    expr.Label{Name: "state", Value: "CH"},
```

在索引中，定向条件被存储为反向索引的形式
age:3 --> 1
state:NY --> 1
state:CH --> 1
如果按照test case中的Assignment来查询，反向索引取得的结果就成为
p0--> [1]
p1--> [1]
刚好maxSize==2，就入选了。

我能想到的work around是：

用户的标签拆分为两个，match两次：
```
        matched := matcher.Match(k, expr.Assignment{
		expr.Label{Name: "age", Value: "4"},
		expr.Label{Name: "state", Value: "NY"},
	})

	matched = matcher.Match(k, expr.Assignment{
		expr.Label{Name: "age", Value: "4"},
		expr.Label{Name: "state", Value: "CH"},
	})
```

这个时候合并的结果为0，因为age对不上。

**Comment by paulllb** [comment]
这个性能方面会大打折扣吧哈哈哈

**Comment by csimplestring** [comment]
并行的查，具体看你的场景

**Comment by echoface** [comment]
这个问题可以参考我的一份实现： https://github.com/echoface/be_indexer 
@paulllb @csimplestring 是可以实现的； 支持论文中没有提到而已；目前已经比较稳定应用在几个公司的线上产品中了
