### ISSUE TITLE
方便解释下benchmark中，20-12,30-12,40-12的意思吗？

### ISSUE THREAD

**Issue by Pickles-wave** [csimplestring/bool-expr-indexer#5]
前面的20，30，40指的是每个规则的表达式个数，12指的是需要查找的规则表达式个数吗？

**Comment by csimplestring** [comment]
@yang0423bobo 你好，12指的是cpu的核心数。我当时的机器12个core。你自己make  go-bench一下，后面的 数字会和你的机器的核心数一样。

It's indicating the number of CPUs that were used to run the benchmark

**Comment by Pickles-wave** [comment]
阿哲，我人傻了，完全理解错误了，那您能解释下您的测试用例怎么构建的吗，比如说10000条规则，每个规则有多少个表达式，需要查询的规则中有几个表达式，总不能全随机的吧（捂脸）

**Comment by csimplestring** [comment]
api/dnf/tools/bench.go 中有我一些测试用到的函数来随机生成表达式。你说的对，就是全随机的。只是总体上保持了1%的概率无法match。

**Comment by Pickles-wave** [comment]
那那个20，30，40又是指什么呢

**Comment by csimplestring** [comment]
key的size，也就是表达式`a=1`中a的长度

**Comment by Pickles-wave** [comment]
好的，我好像明白了，谢谢啦
