### ISSUE TITLE
这里是否有问题？

### ISSUE THREAD

**Issue by Pickles-wave** [csimplestring/bool-expr-indexer#6]
https://github.com/csimplestring/bool-expr-indexer/blob/95e021f67204f13a0a77f440a18cbc31125518cb/api/dnf/tools/bench.go#L67

您好，在这里生成assignment的时候，if flase，value = ""才对吧，按照1%flase，其他均为true来看，如果这里没问题，那最后生成的assignment会有99%的attributes中value = “”。后续match的时候，取出来的postingLists中可能不会有任何元素，因为hashkey为name + “：”+value。

**Comment by Pickles-wave** [comment]
而且在这里直接选择了values[0]作为attribute的value是否过于粗暴，是否可以也用随机的方式从values中选择一个呢？
value := values[rand.Intn(len(values))]

**Comment by csimplestring** [comment]
@Pickles-wave 感谢。不知你有兴趣使用fuzzing test来重新组织一下测试代码吗？起初我只是快速的验证一下我的想法benchmark一下，我认为go 1.18之后推出的fuzz test工具更适合测试现有的代码。

**Comment by Pickles-wave** [comment]
@csimplestring 我对go语言还不太熟悉，只能勉强看懂，我后续有时间的话会尝试的🤦‍🤦‍

这里要是修改为if flase，value = ""的话，也就是assignment会有99%的attributes中value不为空，那这时每次调用match的时间应该就不是您目前的这个测试结果了，大概会慢许多。我目前本地没有环境，没办法立即测试🤦‍
